language: android
jdk: oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - build-tools-28.0.2
    - android-27
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-google-google_play_services
    - addon-google_apis-google-27
