language: android
jdk: oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-28
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-google-google_play_services
    - addon-google_apis-google-28

addons:
  sonarcloud:
    organization: "amrabed-github"

script:
  - sonar-scanner
